name: Auto Merge

on:
  pull_request:
    branches: [master, imgbot]
    types:
      - labeled
  workflow_dispatch:

env:
  BUILD_INFO: "Workflow:${{ github.workflow }} / RunId:${{ github.run_id }} / Ref:${{ github.ref }} / SHA:${{ github.sha }}"

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
     - uses: davideviolante/pr-automerge-action@v1.1.0
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         merge-method: 'rebase' # Default 'squash'
         min-approvals: 2 # Default 2
         base-ref: 'imgbot' # Default 'dev'
